-- #what is the total revenue generated by male vs female ?
select gender , sum(purchase_amount_usd) as revenue 
from customer
group by gender
-- select * from customer limit 20 
-- #which custommer used a discount but still more than the avg. purchase  amount?
SELECT customer_id, purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount_usd > (
    SELECT AVG(purchase_amount_usd)
    FROM customer
);
-- #which are the top 5 products with the highest avg review rating
SELECT item_purchased,
AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;
-- #compare the avg purchased amounts between standard and express shipping 
SELECT shipping_type , AVG(purchase_amount_usd) AS avg_amount
FROM customer 
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type
ORDER BY avg_amount DESC
-- #Do subscribe customer spend more ? compare avg spend and total revenue between subcribe and non-subscribe customer 
SELECT 
    subscription_status,
    SUM(purchase_amount_usd) AS total_revenue,
    AVG(purchase_amount_usd) AS avg_spend
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend DESC;
-- #which 5  products have the highest percentage of purchase with discount applied 
SELECT 
    item_purchased,
    (SUM(purchase_amount_usd) * 100.0 /
        (SELECT SUM(purchase_amount_usd) FROM customer)
    ) AS total_percentage_amount
FROM customer
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY total_percentage_amount DESC
LIMIT 5;
-- #segment customers into new , returning , and loyal baased thier totel number of previous purchases and show the count of each segment
WITH customer_type AS (SELECT customer_id , previous_purchases , 
CASE 
WHEN previous_purchases= 1 THEN 'new'
WHEN previous_purchases  BETWEEN 2 AND 10 THEN 'returning'
ELSE 'loyal'
END AS customer_segment
FROM customer )
SELECT customer_segment , COUNT(*)  AS "number of customers"
FROM customer_type
GROUP BY customer_segment
-- #what are the top 3  most purchased products within each category 
WITH product_count AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_count
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_count,
    ROW_NUMBER() OVER (
        PARTITION BY category 
        ORDER BY total_count DESC
    ) AS rn
FROM product_count;
-- #are customers who are repeat buyers (more than 5 previous )also  likely to subscribe
SELECT subscription_status , count(customer_id) AS total_customer 
FROM customer 
where previous_purchases > 5 
GROUP BY subscription_status 
-- #what is the revenue contribution of each age group 
SELECT 
     age_group,
    SUM(purchase_amount_usd) AS revenue
FROM customer
GROUP BY age_group

